# -*- coding: utf-8 -*-
"""python_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBP4RKEi-_JegKk8zhc6DZafJ9oURsBb
"""

print("hello,Ribani")

"""**print a program**"""

print("My first Ai project")
print("i am learning python")

"""**store and print variable**"""

name=input("enter a name:")
print(name)

"""**Multiple varibale**"""

name="Ribani"
age=19
city="Bandel"
print(name,age,city)

"""**Simple calculator**"""

a=int(input("enter first number:"))
b=int(input("enter first number:"))
print("addition=",a+b)
print("subtractionn=",a-b)
print("multiplication=",a*b)
print("division=",a/b)

"""**Student info program**"""

name=input("enter student name:")
age=int(input("enter age:"))
course=input("enter course name:")

print("student name:",name)
print("student age:",age)
print("student course:",course)